{{- if .Values.service.enabled -}}
{{- $global := . }}
{{- range $name, $config := $global.Values.ports }}
{{- if .expose }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "traefik.fullname" $global }}-{{ $name }}
  labels:
    app.kubernetes.io/name: {{ template "traefik.name" $global }}
    helm.sh/chart: {{ template "traefik.chart" $global }}
    app.kubernetes.io/managed-by: {{ $global.Release.Service }}
    app.kubernetes.io/instance: {{ $global.Release.Name }}
  annotations:
  {{- with $global.Values.service.annotations }}
  {{- toYaml $global | nindent 4 }}
  {{- end }}
spec:
  {{- $type := default "LoadBalancer" $global.Values.service.type }}
  type: {{ $type }}
  {{- with $global.Values.service.spec }}
  {{- toYaml $global | nindent 2 }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "traefik.name" $global }}
    app.kubernetes.io/instance: {{ $global.Release.Name }}
  ports:
  {{- if $config.expose }}
  - port: {{ default $config.port $config.exposedPort }}
    name: {{ $name }}
    targetPort: {{ $name | quote }}
    protocol: {{ $config.protocol }}
    {{- if $config.nodePort }}
    nodePort: {{ $config.nodePort }}
    {{- end }}
  {{- end }}
  {{- if eq $type "LoadBalancer" }}
  {{- with $global.Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml $global | nindent 2 }}
  {{- end -}}
  {{- end -}}
  {{- with $global.Values.service.externalIPs }}
  externalIPs:
  {{- toYaml $global | nindent 2 }}
  {{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
